version : '1'

services:
  semantic-similarity:
    build: 
      context: ./Semantic\ Similarity/
    ports: 
      - "8081:8081"

  topic-modeling:
    build:
      context: ./Topic\ Modeling/
    ports:
      - "8082:8082"

  combiner:
    build:
      context: ./combiner/
    ports:
      - "5000:5000" 
